analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#706567'
    - '#3F3E4D'
    - '#A9A2AC'
    - '#D9D6D8'
  brandStrength: 0
  lightness: 0.657094
  rhythmicContrast: 0.192567
  saturation: 0.5
cta: {}
layout_spectrum: 0.44722
name: The Object Studio
opengraph: {}
purpose: []
typography_spectrum: 0.73496
