name: The Object Studio
favicon: null
layout_spectrum: 0.44722
typography_spectrum: 0.73496
title: The Object Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#706567'
    - '#3f3e4d'
    - '#a9a2ac'
    - '#d9d6d8'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
